public class CL_0808_CalEva 
{
    // Class Variable
    Public Integer Num     {get;set;}
    Public Integer N      {set;get;}
    Public Integer Num2    {set;get;}
    Public Integer Square   {get;set;}
     // Logic
     
    public void fact()
    {	
        N=1;
        for(integer i =1; i<=Num ; i++ )
        {
            N = N * i ;
            
        }
        
            
    }
    public void M()
    {    
        Square = 1;
        Square= Num2 * Num2;
    }
     
    
}