public class ClassToAddandMultiply 
{
    public static integer  add(integer A , Integer B) // Taking integers
    {
        Integer Result = A + B;
        return Result;
    }
    public static string  concatenate(String A, String B) // Taking Strings
    {
        String Result =  A + B;
        Return Result;
    }
    public static Decimal Multiply(Decimal A, Decimal B) // Taking Decimals
    {
        Decimal Result = A * B;
        Return Result;
    }

}